name: stagexl_isometric
version: 0.2.1
author: Bernhard Pichler <support@stagexl.org>
description: An isometric graphics extension for StageXL.
homepage: https://github.com/bp74/StageXL_Isometric

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  stagexl: '>=1.4.1 <2.0.0'

dev_dependencies:
  pedantic: any
  build_runner: any
  build_test: any
  build_web_compilers: any